### PR TITLE
fix: updates upf configuration when there's a modification

### LINKED ISSUE #196: The Configuration order causes PFCP Association Request Failure
The following configuration order in webconsole causes PFCP Association Setup failure.

- Create a network slice with empty device group
- Create a device group
- Create a subscriber

SMF log:

`2023-11-30T20:55:48.294Z [smf] 2023-11-30T20:55:48Z [ERRO][SMF][PFCP] Handle PFCP Association Setup success Response, DNN mismatch, [internet] is not configured`

Please check the following issue for more details:
https://github.com/omec-project/webconsole/issues/89

### PR DESCRIPTION
**Pull request by gruyaume**
## Description

The SMF has an issue where where it was not possible to add a device group to an empty network slice. There were two root causes that caused this problem:
1. `compareUPNodesConfigs` used to return `match = true` which would cause `UpdatedSmfConfig.ModUPNodes` to not contain the updated upf content. The changes for this are in [factory/config.go](https://github.com/omec-project/smf/pull/202/files#diff-7d2ff7ee141e8dcfa4279b4e2349e12cb0a3f1c394ca4957f2f4792e56a6b5a4).
2. `UpdateSmfUserPlaneNode` would result in loosing the Links between the gNB and UPF. The reason was that this method would first delete and then create a new user plane object. The new user plane object would not contain the required Links because those are created by `InsertUPNodeLinks` only when there are changes to links (not on user plane change). Here instead of deleting the object, we simply edit it and maintain the existing Links. The changes for this are in [context/user_plane_information.go](https://github.com/omec-project/smf/pull/202/files#diff-df840037f2bd2bc826009a1ce6cbd92e6f394834634daf8903acbdfebde48709).

Here I also added the necessary unit tests to validate the expected behavior of the modified methods.

Fixes #196

### CODE REVIEW

**Comment by thakurajayL** [comment]
ok to test

File: context/user_plane_information.go [hunk 1]
```diff
@@ -354,13 +355,73 @@ func (upi *UserPlaneInformation) InsertSmfUserPlaneNode(name string, node *facto
...
 }
 
-// update UPF info
-func (upi *UserPlaneInformation) UpdateSmfUserPlaneNode(name string, node *factory.UPNode) error {
-	//What all to update- nssai/dnn info
-	logger.UPNodeLog.Infof("UPNode[%v] to update, content[%v]\n", name, node)
-	logger.UPNodeLog.Debugf("content of map[UPNodes] %v \n", upi.UPNodes)
-	upi.DeleteSmfUserPlaneNode(name, node)
-	upi.InsertSmfUserPlaneNode(name, node)
+func (upi *UserPlaneInformation) UpdateSmfUserPlaneNode(name string, newNode *factory.UPNode) error {
```
Comment (ghislainbourgeois) [inline context/user_plane_information.go:358]: As this PR adds a lot of logic to this function, can you also add a docstring?

File: context/user_plane_information.go [hunk 2]
```diff
@@ -354,13 +355,73 @@ func (upi *UserPlaneInformation) InsertSmfUserPlaneNode(name string, node *facto
...
+	existingNode, exists := upi.UPNodes[name]
+	if !exists {
+		return fmt.Errorf("UPNode [%v] does not exist", name)
+	}
+
+	existingNode.Port = newNode.Port
+
+	if existingNode.Type == UPNODE_AN {
+		existingNode.ANIP = net.ParseIP(newNode.ANIP)
+		return nil
```
Comment (ghislainbourgeois) [inline context/user_plane_information.go:370]: Do we really want to return here? I see some code towards the end of function that looks general, like a logging call and some assignments.

File: context/user_plane_information.go [hunk 3]
```diff
@@ -354,13 +355,73 @@ func (upi *UserPlaneInformation) InsertSmfUserPlaneNode(name string, node *facto
...
+	}
+
+	if existingNode.Type == UPNODE_UPF {
+		var nodeIdType uint8
+		var ip net.IP
+
+		ip = net.ParseIP(newNode.NodeID)
```
Comment (ghislainbourgeois) [inline context/user_plane_information.go:377]:
```suggestion

		ip := net.ParseIP(newNode.NodeID)
```

**Comment by ghislainbourgeois** [comment]
Also, can you please squash your commits?

**Comment by gab-arrobo** [comment]
> Also, can you please squash your commits?

FYI, there is no need to squash the commits in the PR because they get squashed when the PR is merged (configured by default in the repos: `Squash and merge`
image

File: context/user_plane_information.go (hunk 1 above)
Comment (gruyaume) [reply context/user_plane_information.go:361]: Done

File: context/user_plane_information.go (hunk 2 above)
Comment (gruyaume) [reply context/user_plane_information.go]: Done, we're now following the same structure as the insert func

**Review by ghislainbourgeois — APPROVED** [review]

**Comment by gruyaume** [comment]
@gab-arrobo can you please review this PR?

**Comment by gab-arrobo** [comment]
> @gab-arrobo can you please review this PR?

@thakurajayL, did you have a chance to review this PR?

File: context/user_plane_information.go [hunk 4]
```diff
@@ -354,13 +355,77 @@ func (upi *UserPlaneInformation) InsertSmfUserPlaneNode(name string, node *facto
...
-	upi.InsertSmfUserPlaneNode(name, node)
+// Update an existing User Plane Node.
+// If the node is of type AN, then the node is updated with the new port.
+// If the node is of type UPF, then the node is updated with the new port and the new UPF information.
+func (upi *UserPlaneInformation) UpdateSmfUserPlaneNode(name string, newNode *factory.UPNode) error {
+	logger.UPNodeLog.Infof("UPNode [%v] to update, content[%v]\n", name, newNode)
+
+	existingNode, exists := upi.UPNodes[name]
+	if !exists {
+		return fmt.Errorf("UPNode [%v] does not exist", name)
```
Comment (gab-arrobo) [inline context/user_plane_information.go:366]: Given that `names` is string, why not the following?
```suggestion
		return fmt.Errorf("UPNode [%s] does not exist", name)
```

File: context/user_plane_information.go [hunk 5]
```diff
@@ -354,13 +355,77 @@ func (upi *UserPlaneInformation) InsertSmfUserPlaneNode(name string, node *facto
...
+	default:
+		logger.InitLog.Warningf("invalid UPNodeType: %s\n", existingNode.Type)
+	}
+
+	upi.UPNodes[name] = existingNode
+
+	ipStr := existingNode.NodeID.ResolveNodeIdToIp().String()
+	upi.UPFIPToName[ipStr] = name
+
+	logger.CtxLog.Infof("UPNode [%v] updated successfully", name)
```
Comment (gab-arrobo) [inline context/user_plane_information.go:428]:
```suggestion
	logger.CtxLog.Infof("UPNode [%s] updated successfully", name)
```

File: context/user_plane_information_test.go [hunk 6]
```diff
@@ -219,17 +221,92 @@ func TestGenerateDefaultPath(t *testing.T) {
...
+	// Create an existing UPNode with a specific UPF instance
+	originalUPF := context.NewUPF(&nodeID, nil)
+	existingNode := &context.UPNode{
+		Type:   "UPF",
+		NodeID: nodeID,
+		Port:   1234,
+		UPF:    originalUPF,
+		Links: []*context.UPNode{
+			{
+				Type: context.UPNODE_AN,
```
Comment (gab-arrobo) [inline context/user_plane_information_test.go:249]: Given that there is more code in the `case UPNODE_UPF:`, would it be better to have this test for `UPNODE_UPF` instead of `UPNOD_AN`?

**Review by gab-arrobo — DISMISSED** [review]
+1 (tested changes with AiaB)

File: context/user_plane_information_test.go (hunk 6 above)
Comment (gruyaume) [reply context/user_plane_information_test.go:249]: We could, the reason I used the `AN` is that it was with such a link that I noticed the issue.

**Review by gab-arrobo — APPROVED** [review]
+1
